<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Version>$(CmdlessRuntimeVersion)</Version>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>Cmdless.UI</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Cmdless.UI.SDK/Cmdless.UI.SDK.csproj" />
  </ItemGroup>

</Project>